services:
  code-server:
    image: "lscr.io/linuxserver/code-server:latest"
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - "./config:/config"
      - "./project:/coder/project"
      - "./data:/coder/./local/share/code-server"
      - "/home/ubuntu/docker:/config/docker"
